<?php

return [
    'publication_states' => [
        "draft" => "draft",
        "accepted" => "accepted",
        'submitted' => 'submitted',
        'published' => 'published',
        'updated' => 'updated',
    ],
    'server_states' => [
        "deleted" => "deleted",
        "inprogress" => "inprogress",
        "published" => "published",
        "released" => "released",
        "editor_accepted" => "editor_accepted",
        "approved" => "approved",
        "rejected_reviewer" => "rejected_reviewer",
        "rejected_editor" => "rejected_editor",
        "reviewed" => "reviewed",
    ],
    'mimetypes_allowed' => [
        "pdf" => "application/pdf",
        "txt|asc|c|cc|h|srt" => "text/plain",
        "htm|html" => "text/html",
        "png" => "image/png",
        "jpg|jpeg|jpe" => "image/jpeg",
    ],
    'name_types' => [
        'personal' => 'Personal',
        'organizational' => 'Organizational',
    ],
    'contributor_types' => [
        'contact_person' => 'ContactPerson',
        'data_collector' => 'DataCollector',
        'data_curator' => 'DataCurator',
        'data_manager' => 'DataManager',
        'Distributor' => 'Distributor',
        'editor' => 'Editor',
        'hosting_institution' => 'HostingInstitution',
        'producer' => 'Producer',
        'poroject_leader' => 'ProjectLeader',
        'project_manager' => 'ProjectManager',
        'project_member' => 'ProjectMember',
        'registration_agency' => 'RegistrationAgency',
        'registration_authority' => 'RegistrationAuthority',
        'related_person' => 'RelatedPerson',
        'researcher' => 'Researcher',
        'research_group' => 'ResearchGroup',
        'rights_holder' => 'RightsHolder',
        'sponsor' => 'Sponsor',
        'supervisor' => 'Supervisor',
        'work_package_leader' => 'WorkPackageLeader',
        'other' => 'Other',
    ],
];
